// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gtbweb.Models;

namespace gtbweb.mvc.Migrations.ServiceDb
{
    [DbContext(typeof(ServiceDbContext))]
    partial class ServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("gtbweb.Models.Proficiency", b =>
                {
                    b.Property<int>("ProficiencyID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PercentageScore");

                    b.Property<int>("ProfileID");

                    b.Property<int?>("SkillID");

                    b.HasKey("ProficiencyID");

                    b.HasIndex("ProfileID");

                    b.HasIndex("SkillID");

                    b.ToTable("Proficiencies");
                });

            modelBuilder.Entity("gtbweb.Models.Profile", b =>
                {
                    b.Property<int>("ProfileID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("About");

                    b.Property<string>("Designation");

                    b.Property<string>("Image");

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<string>("UserID");

                    b.HasKey("ProfileID");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("gtbweb.Models.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ServiceDescription");

                    b.Property<string>("Title");

                    b.HasKey("ServiceID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("gtbweb.Models.ServiceCollection", b =>
                {
                    b.Property<int>("ServiceCollectionID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ProficiencyID");

                    b.Property<int>("ServiceID");

                    b.HasKey("ServiceCollectionID");

                    b.HasIndex("ProficiencyID");

                    b.HasIndex("ServiceID");

                    b.ToTable("ServiceCollections");
                });

            modelBuilder.Entity("gtbweb.Models.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("SkillID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("gtbweb.Models.Proficiency", b =>
                {
                    b.HasOne("gtbweb.Models.Profile", "Profile")
                        .WithMany("Proficiencies")
                        .HasForeignKey("ProfileID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("gtbweb.Models.Skill", "Skill")
                        .WithMany("Proficiencies")
                        .HasForeignKey("SkillID");
                });

            modelBuilder.Entity("gtbweb.Models.ServiceCollection", b =>
                {
                    b.HasOne("gtbweb.Models.Proficiency", "Proficiency")
                        .WithMany("ServiceCollections")
                        .HasForeignKey("ProficiencyID");

                    b.HasOne("gtbweb.Models.Service", "Service")
                        .WithMany("ServiceCollections")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
